### ISSUE TITLE
Consider making the top bar stick to the navigation

### ISSUE THREAD

**Issue by FireIsGood** [syeopite/priviblur#176]
Currently the top bar does not stick to the top of the screen. As an infinite scroll type app, this makes the search bar unusable for a lot of the UI.

If you want to make it sticky it's basicllly like 5 lines, too:

```css
.navbar {
  position: sticky;
  top: 0;
  box-shadow: 0 0 8px var(--color-background), 0 0 4px var(--color-background);
  z-index: 100;
}
```

There's also a little box shadow included in that snippet, as a treat!
